-- BNDR VoiceEngine 3.2.0 — forward production migration
-- Safe for a fresh Supabase project and for the v5 schema already in service.
-- All dates, periods, trials, grace windows, and usage buckets are UTC.

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

GRANT USAGE ON SCHEMA public TO authenticated;

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = ''
AS $$
BEGIN
  NEW.updated_at = timezone('utc', now());
  RETURN NEW;
END;
$$;

-- ---------------------------------------------------------------------------
-- Accounts and entitlements
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.subscriptions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  stripe_customer_id TEXT UNIQUE,
  stripe_subscription_id TEXT UNIQUE,
  status TEXT NOT NULL DEFAULT 'trial',
  plan_interval TEXT,
  price_id TEXT,
  quantity INTEGER NOT NULL DEFAULT 1 CHECK (quantity > 0),
  current_period_start TIMESTAMPTZ,
  current_period_end TIMESTAMPTZ,
  grace_ends_at TIMESTAMPTZ,
  cancel_at_period_end BOOLEAN NOT NULL DEFAULT FALSE,
  trial_ends_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('utc', now()) + INTERVAL '7 days'),
  canceled_at TIMESTAMPTZ,
  latest_invoice_id TEXT,
  last_reconciled_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now())
);

ALTER TABLE public.subscriptions
  ADD COLUMN IF NOT EXISTS price_id TEXT,
  ADD COLUMN IF NOT EXISTS quantity INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS grace_ends_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS canceled_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS latest_invoice_id TEXT,
  ADD COLUMN IF NOT EXISTS last_reconciled_at TIMESTAMPTZ;

ALTER TABLE public.subscriptions DROP CONSTRAINT IF EXISTS subscriptions_status_check;
ALTER TABLE public.subscriptions
  ADD CONSTRAINT subscriptions_status_check
  CHECK (status IN ('trial','active','grace','past_due','paused','canceled','expired'));
ALTER TABLE public.subscriptions DROP CONSTRAINT IF EXISTS subscriptions_plan_interval_check;
ALTER TABLE public.subscriptions
  ADD CONSTRAINT subscriptions_plan_interval_check
  CHECK (plan_interval IS NULL OR plan_interval IN ('weekly','monthly','annual','metered','lifetime'));

CREATE INDEX IF NOT EXISTS idx_subscriptions_customer ON public.subscriptions(stripe_customer_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_external ON public.subscriptions(stripe_subscription_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_status_end ON public.subscriptions(status, current_period_end);

DROP TRIGGER IF EXISTS trg_subscriptions_updated_at ON public.subscriptions;
CREATE TRIGGER trg_subscriptions_updated_at
BEFORE UPDATE ON public.subscriptions
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE IF NOT EXISTS public.billing_events (
  stripe_event_id TEXT PRIMARY KEY,
  event_type TEXT NOT NULL,
  livemode BOOLEAN NOT NULL,
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  processing_state TEXT NOT NULL DEFAULT 'processing'
    CHECK (processing_state IN ('processing','processed','failed','ignored')),
  processing_error TEXT,
  attempt_count INTEGER NOT NULL DEFAULT 1,
  received_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  processed_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS public.entitlement_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  source_event_id TEXT,
  from_status TEXT,
  to_status TEXT NOT NULL,
  reason TEXT NOT NULL,
  effective_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS idx_entitlement_history_user
  ON public.entitlement_history(user_id, effective_at DESC);

-- ---------------------------------------------------------------------------
-- Product state
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.usage_tracking (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  request_date DATE NOT NULL DEFAULT (timezone('utc', now()))::date,
  request_count INTEGER NOT NULL DEFAULT 0 CHECK (request_count >= 0),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  UNIQUE(user_id, request_date)
);
ALTER TABLE public.usage_tracking
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now());

CREATE TABLE IF NOT EXISTS public.voice_profiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  machine_file JSONB,
  analysis JSONB,
  provider TEXT NOT NULL DEFAULT 'anthropic',
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  UNIQUE(user_id, name)
);
-- v5 briefly stored a 500-character sample preview. Production 3.2.0 removes
-- it so the database cannot retain writing samples.
ALTER TABLE public.voice_profiles DROP COLUMN IF EXISTS sample_preview;
ALTER TABLE public.voice_profiles DROP CONSTRAINT IF EXISTS voice_profiles_name_check;
ALTER TABLE public.voice_profiles
  ADD CONSTRAINT voice_profiles_name_check
  CHECK (CHAR_LENGTH(BTRIM(name)) BETWEEN 1 AND 120) NOT VALID;
ALTER TABLE public.voice_profiles DROP CONSTRAINT IF EXISTS voice_profiles_provider_check;
ALTER TABLE public.voice_profiles
  ADD CONSTRAINT voice_profiles_provider_check
  CHECK (provider IN ('anthropic','deepseek','openai')) NOT VALID;

DROP TRIGGER IF EXISTS trg_voice_profiles_updated_at ON public.voice_profiles;
CREATE TRIGGER trg_voice_profiles_updated_at
BEFORE UPDATE ON public.voice_profiles
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE IF NOT EXISTS public.user_preferences (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  tour_completed_at TIMESTAMPTZ,
  tour_skipped_at TIMESTAMPTZ,
  preferred_provider TEXT CHECK (preferred_provider IN ('anthropic','deepseek','openai')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now())
);

DROP TRIGGER IF EXISTS trg_user_preferences_updated_at ON public.user_preferences;
CREATE TRIGGER trg_user_preferences_updated_at
BEFORE UPDATE ON public.user_preferences
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE IF NOT EXISTS public.error_reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  correlation_id UUID NOT NULL UNIQUE,
  error_code TEXT NOT NULL CHECK (error_code ~ '^VE-[A-Z0-9_]{2,40}$'),
  message TEXT NOT NULL CHECK (char_length(message) BETWEEN 1 AND 2000),
  route TEXT,
  app_version TEXT NOT NULL,
  provider TEXT,
  browser_context JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now())
);
CREATE INDEX IF NOT EXISTS idx_error_reports_user_created
  ON public.error_reports(user_id, created_at DESC);

-- ---------------------------------------------------------------------------
-- Account bootstrap
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  INSERT INTO public.subscriptions(user_id, status, trial_ends_at)
  VALUES (NEW.id, 'trial', timezone('utc', now()) + INTERVAL '7 days')
  ON CONFLICT (user_id) DO NOTHING;

  INSERT INTO public.user_preferences(user_id)
  VALUES (NEW.id)
  ON CONFLICT (user_id) DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_new_user_subscription ON auth.users;
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Backfill existing accounts without mutating paid entitlement rows.
INSERT INTO public.subscriptions(user_id, status, trial_ends_at)
SELECT u.id, 'trial', u.created_at + INTERVAL '7 days'
FROM auth.users u
ON CONFLICT (user_id) DO NOTHING;
INSERT INTO public.user_preferences(user_id)
SELECT id FROM auth.users
ON CONFLICT (user_id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- Atomic usage and entitlement gate
-- ---------------------------------------------------------------------------
-- The v5 RPC returned a three-column table. PostgreSQL cannot change OUT
-- columns through CREATE OR REPLACE, so replace the signature transactionally.
DROP FUNCTION IF EXISTS public.check_and_increment_usage(UUID);
CREATE OR REPLACE FUNCTION public.check_and_increment_usage(p_user_id UUID)
RETURNS TABLE(allowed BOOLEAN, current_count INTEGER, daily_limit INTEGER, entitlement_status TEXT)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_sub public.subscriptions%ROWTYPE;
  v_limit INTEGER := 0;
  v_count INTEGER := 0;
  v_status TEXT := 'expired';
  v_today DATE := (timezone('utc', now()))::date;
BEGIN
  IF (SELECT auth.uid()) IS NULL OR (SELECT auth.uid()) <> p_user_id THEN
    RAISE EXCEPTION 'forbidden' USING ERRCODE = '42501';
  END IF;

  SELECT * INTO v_sub
  FROM public.subscriptions
  WHERE user_id = p_user_id
  FOR UPDATE;

  IF NOT FOUND THEN
    INSERT INTO public.subscriptions(user_id) VALUES (p_user_id)
    RETURNING * INTO v_sub;
  END IF;

  v_status := v_sub.status;
  IF v_sub.status = 'trial' AND v_sub.trial_ends_at > timezone('utc', now()) THEN
    v_limit := 5;
  ELSIF v_sub.status = 'active'
    AND (v_sub.current_period_end IS NULL OR v_sub.current_period_end > timezone('utc', now())) THEN
    v_limit := CASE WHEN v_sub.plan_interval = 'lifetime' THEN 1000000 ELSE 50 END;
  ELSIF v_sub.status IN ('grace','past_due')
    AND v_sub.grace_ends_at > timezone('utc', now()) THEN
    v_status := 'grace';
    v_limit := 50;
  ELSE
    v_status := 'expired';
    v_limit := 0;
  END IF;

  INSERT INTO public.usage_tracking(user_id, request_date, request_count)
  VALUES (p_user_id, v_today, 0)
  ON CONFLICT (user_id, request_date) DO NOTHING;

  SELECT request_count INTO v_count
  FROM public.usage_tracking
  WHERE user_id = p_user_id AND request_date = v_today
  FOR UPDATE;

  IF v_count >= v_limit THEN
    RETURN QUERY SELECT false, v_count, v_limit, v_status;
    RETURN;
  END IF;

  UPDATE public.usage_tracking
  SET request_count = request_count + 1, updated_at = timezone('utc', now())
  WHERE user_id = p_user_id AND request_date = v_today
  RETURNING request_count INTO v_count;

  RETURN QUERY SELECT true, v_count, v_limit, v_status;
END;
$$;

REVOKE ALL ON FUNCTION public.check_and_increment_usage(UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.check_and_increment_usage(UUID) FROM anon;
GRANT EXECUTE ON FUNCTION public.check_and_increment_usage(UUID) TO authenticated;

-- ---------------------------------------------------------------------------
-- Row-level security
-- ---------------------------------------------------------------------------
ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.billing_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.entitlement_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.usage_tracking ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.voice_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.error_reports ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "sub_select_own" ON public.subscriptions;
CREATE POLICY "sub_select_own" ON public.subscriptions
FOR SELECT TO authenticated USING ((SELECT auth.uid()) = user_id);

DROP POLICY IF EXISTS "entitlement_history_select_own" ON public.entitlement_history;
CREATE POLICY "entitlement_history_select_own" ON public.entitlement_history
FOR SELECT TO authenticated USING ((SELECT auth.uid()) = user_id);

DROP POLICY IF EXISTS "usage_select_own" ON public.usage_tracking;
CREATE POLICY "usage_select_own" ON public.usage_tracking
FOR SELECT TO authenticated USING ((SELECT auth.uid()) = user_id);

DROP POLICY IF EXISTS "profiles_all_own" ON public.voice_profiles;
CREATE POLICY "profiles_all_own" ON public.voice_profiles
FOR ALL TO authenticated
USING ((SELECT auth.uid()) = user_id)
WITH CHECK ((SELECT auth.uid()) = user_id);

DROP POLICY IF EXISTS "preferences_all_own" ON public.user_preferences;
CREATE POLICY "preferences_all_own" ON public.user_preferences
FOR ALL TO authenticated
USING ((SELECT auth.uid()) = user_id)
WITH CHECK ((SELECT auth.uid()) = user_id);

DROP POLICY IF EXISTS "error_reports_insert_own" ON public.error_reports;
CREATE POLICY "error_reports_insert_own" ON public.error_reports
FOR INSERT TO authenticated
WITH CHECK ((SELECT auth.uid()) = user_id);
DROP POLICY IF EXISTS "error_reports_select_own" ON public.error_reports;
CREATE POLICY "error_reports_select_own" ON public.error_reports
FOR SELECT TO authenticated
USING ((SELECT auth.uid()) = user_id);

REVOKE ALL ON TABLE public.subscriptions, public.billing_events, public.entitlement_history,
  public.usage_tracking, public.voice_profiles, public.user_preferences, public.error_reports
  FROM anon;
REVOKE ALL ON TABLE public.subscriptions, public.billing_events, public.entitlement_history,
  public.usage_tracking, public.voice_profiles, public.user_preferences, public.error_reports
  FROM authenticated;
GRANT SELECT ON public.subscriptions, public.entitlement_history, public.usage_tracking TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.voice_profiles, public.user_preferences TO authenticated;
GRANT SELECT, INSERT ON public.error_reports TO authenticated;

-- ---------------------------------------------------------------------------
-- Storage: private, user-scoped profile exports
-- ---------------------------------------------------------------------------
INSERT INTO storage.buckets(id, name, public, file_size_limit, allowed_mime_types)
VALUES ('voice-profile-exports', 'voice-profile-exports', false, 1048576,
  ARRAY['application/json','text/plain','text/markdown'])
ON CONFLICT (id) DO UPDATE
SET public = false, file_size_limit = EXCLUDED.file_size_limit,
    allowed_mime_types = EXCLUDED.allowed_mime_types;

DROP POLICY IF EXISTS "voice_exports_select_own" ON storage.objects;
CREATE POLICY "voice_exports_select_own" ON storage.objects
FOR SELECT TO authenticated
USING (bucket_id = 'voice-profile-exports'
  AND (storage.foldername(name))[1] = (SELECT auth.uid())::text);

DROP POLICY IF EXISTS "voice_exports_insert_own" ON storage.objects;
CREATE POLICY "voice_exports_insert_own" ON storage.objects
FOR INSERT TO authenticated
WITH CHECK (bucket_id = 'voice-profile-exports'
  AND (storage.foldername(name))[1] = (SELECT auth.uid())::text);

DROP POLICY IF EXISTS "voice_exports_update_own" ON storage.objects;
CREATE POLICY "voice_exports_update_own" ON storage.objects
FOR UPDATE TO authenticated
USING (bucket_id = 'voice-profile-exports'
  AND owner_id = (SELECT auth.uid())::text)
WITH CHECK (bucket_id = 'voice-profile-exports'
  AND (storage.foldername(name))[1] = (SELECT auth.uid())::text);

DROP POLICY IF EXISTS "voice_exports_delete_own" ON storage.objects;
CREATE POLICY "voice_exports_delete_own" ON storage.objects
FOR DELETE TO authenticated
USING (bucket_id = 'voice-profile-exports'
  AND owner_id = (SELECT auth.uid())::text);
